from CreateOne import *
class CreateMany:
    def firstScreen(parent):  
        parent.createOne.item        (parent,  10, 100, "imagens/Medias/pc_m.jpg",          "Supremacy Ultra: o ápice da tecnologia encapsulada em um computador excepcionalmente poderoso e esteticamente impressionante.")
        parent.createOne.item   (parent, 330, 100, "imagens/Medias/teclado_m.jpg",     "ultra type: teclado mecânico com uma experiência de digitação excepcional! Combina durabilidade, precisão e conforto em um design elegante e excêntrico.")
        parent.createOne.item   (parent, 650, 100, "imagens/Medias/monitor_m.jpg",     "VisionXtreme: Com resolução Ultra HD 4K, taxa de atualização de 144Hz e tecnologia HDR, oferece imagens nítidas e vibrantes para uma experiência visual imersiva.")
        parent.createOne.item     (parent, 970, 100, "imagens/Medias/mouse_m.jpg",       "PhantomGrip: o Mouse Gamer de Elite Projetado para proporcionar precisão, velocidade e conforto como nenhum outro.")
        parent.createOne.item(parent,  10, 240, "imagens/Medias/processador_m.jpg", "HyperCore: Perfeito para Desempenho Computacional! Equipado com tecnologia de ponta, tem potência para lidar com as tarefas mais exigentes")
        parent.createOne.item       (parent, 330, 240, "imagens/Medias/ssd_m.jpg",         "TurboDrive: o SSD de Elite completo! Com capacidades de armazenamento e velocidades de leitura/gravação ultra-rápidas e alta confiabilidade")
        parent.createOne.item    (parent, 650, 240, "imagens/Medias/cooler_m.jpg",      "FrostBlast: o Cooler perfeito para seu Desempenho de Refrigeração! Oferece resfriamento excepcional e silencio para seu sistema.")
        parent.createOne.item(parent, 970, 240, "imagens/Medias/placaVideo_m.jpg",  "TurBoost 9000X tem uma potência de processamento gráfico projetada para elevar sua experiência a novos patamares. Com velocidade, eficiência e potência líderes de mercado") 
        parent.createOne.item  (parent,  10, 380, "imagens/Medias/mousepad_m.jpg",    "HyperGlide Pro: o Mousepad de Elite para sua Precisão e Conforto de Movimento!") 
        parent.createOne.item      (parent, 330, 380, "imagens/Medias/fone_m.jpg",        "SonicBlast 8000X: projetados para proporcionar áudio imersivo e de alta qualidade. Com drivers de última geração e tecnologia de cancelamento de ruído ativo.") 
        parent.createOne.item       (parent, 650, 380, "imagens/Medias/ram_m.jpg",           "RAM Triforce: uma solução poderosa que oferece não uma, mas três memórias RAM de alta velocidade, Com capacidade total de 24GB (3x8GB)") 
        parent.createOne.item  (parent, 970, 380, "imagens/Medias/gabinete_m.jpg",      "Gamer Turbo X, uma escolha para os entusiastas de PC que buscam o máximo em desempenho e estilo. Com iluminação RGB personalizável e amplo espaço interno") 


    def itemsToAdd(parent):
        pc_add =          parent.createOne.button(parent, "+",  100, 190, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        teclado_add =     parent.createOne.button(parent, "+",  420, 190, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        monitor_add =     parent.createOne.button(parent, "+",  740, 190, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        mouse_add =       parent.createOne.button(parent, "+", 1060, 190, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        processador_add = parent.createOne.button(parent, "+",  100, 330, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        ssd_add =         parent.createOne.button(parent, "+",  420, 330, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        cooler_add =      parent.createOne.button(parent, "+",  740, 330, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        placaVideo_add =  parent.createOne.button(parent, "+", 1060, 330, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        mousepad_add =    parent.createOne.button(parent, "+",  100, 470, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        fone_add =        parent.createOne.button(parent, "+",  420, 470, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        ram_add =         parent.createOne.button(parent, "+",  740, 470, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        gabinete_add =    parent.createOne.button(parent, "+", 1060, 470, 25, 25, 'QPushButton {background-color:#000540; color: white; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        
        pc_add.clicked.connect         (lambda: parent.onAddToCartClicked('pc'))
        teclado_add.clicked.connect    (lambda: parent.onAddToCartClicked('teclado'))
        monitor_add.clicked.connect    (lambda: parent.onAddToCartClicked('monitor'))
        mouse_add.clicked.connect      (lambda: parent.onAddToCartClicked('mouse'))       
        mousepad_add.clicked.connect   (lambda: parent.onAddToCartClicked('mousepad'))
        processador_add.clicked.connect(lambda: parent.onAddToCartClicked('processador'))
        ssd_add.clicked.connect        (lambda: parent.onAddToCartClicked('ssd'))
        cooler_add.clicked.connect     (lambda: parent.onAddToCartClicked('cooler'))
        placaVideo_add.clicked.connect (lambda: parent.onAddToCartClicked('placaVideo'))
        fone_add.clicked.connect       (lambda: parent.onAddToCartClicked('fone'))
        ram_add.clicked.connect        (lambda: parent.onAddToCartClicked('ram'))
        gabinete_add.clicked.connect   (lambda: parent.onAddToCartClicked('gabinete'))


    def itemsToRemove(parent):
        pc_remove =          parent.createOne.button(parent, "-",  100, 190, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        teclado_remove =     parent.createOne.button(parent, "-",  420, 190, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        monitor_remove =     parent.createOne.button(parent, "-",  740, 190, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        mouse_remove =       parent.createOne.button(parent, "-", 1060, 190, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        processador_remove = parent.createOne.button(parent, "-",  100, 330, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        ssd_remove =         parent.createOne.button(parent, "-",  420, 330, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        cooler_remove =      parent.createOne.button(parent, "-",  740, 330, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        placaVideo_remove =  parent.createOne.button(parent, "-", 1060, 330, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        mousepad_remove =    parent.createOne.button(parent, "-",  100, 470, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        fone_remove =        parent.createOne.button(parent, "-",  420, 470, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        ram_remove =         parent.createOne.button(parent, "-",  740, 470, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')
        gabinete_remove =    parent.createOne.button(parent, "-", 1060, 470, 25, 25, 'QPushButton {background-color:#D40000; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 5px 0}')

        pc_remove.clicked.connect         (lambda: parent.removeFromCart('pc'))
        teclado_remove.clicked.connect    (lambda: parent.removeFromCart('teclado'))
        monitor_remove.clicked.connect    (lambda: parent.removeFromCart('monitor'))
        mouse_remove.clicked.connect      (lambda: parent.removeFromCart('mouse'))       
        processador_remove.clicked.connect(lambda: parent.removeFromCart('processador'))
        ssd_remove.clicked.connect        (lambda: parent.removeFromCart('ssd'))
        cooler_remove.clicked.connect     (lambda: parent.removeFromCart('cooler'))
        placaVideo_remove.clicked.connect (lambda: parent.removeFromCart('placaVideo'))
        mousepad_remove.clicked.connect   (lambda: parent.removeFromCart('mousepad'))
        fone_remove.clicked.connect       (lambda: parent.removeFromCart('fone'))
        ram_remove.clicked.connect        (lambda: parent.removeFromCart('ram'))
        gabinete_remove.clicked.connect   (lambda: parent.removeFromCart('gabinete'))


    def itemDetails(parent):
        pc_details =          parent.createOne.button(parent, "?",  100, 190, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        teclado_details =     parent.createOne.button(parent, "?",  420, 190, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        monitor_details =     parent.createOne.button(parent, "?",  740, 190, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        mouse_details =       parent.createOne.button(parent, "?", 1060, 190, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        processador_details = parent.createOne.button(parent, "?",  100, 330, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        ssd_details =         parent.createOne.button(parent, "?",  420, 330, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        cooler_details =      parent.createOne.button(parent, "?",  740, 330, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        placaVideo_details =  parent.createOne.button(parent, "?", 1060, 330, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        mousepad_details =    parent.createOne.button(parent, "?",  100, 470, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        fone_details =        parent.createOne.button(parent, "?",  420, 470, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        ram_details =         parent.createOne.button(parent, "?",  740, 470, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')
        gabinete_details =    parent.createOne.button(parent, "?", 1060, 470, 25, 25, 'QPushButton {background-color:#FFFFFF; color: black; font:bold; font-size:24px; border-radius:12px; padding: 0 0 0 2px}')

        pc_details.clicked.connect         (lambda: parent.productDetails('pc', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        teclado_details.clicked.connect    (lambda: parent.productDetails('teclado', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        monitor_details.clicked.connect    (lambda: parent.productDetails('monitor', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        mouse_details.clicked.connect      (lambda: parent.productDetails('mouse', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))       
        processador_details.clicked.connect(lambda: parent.productDetails('processador', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        ssd_details.clicked.connect        (lambda: parent.productDetails('ssd', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        cooler_details.clicked.connect     (lambda: parent.productDetails('cooler', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        placaVideo_details.clicked.connect (lambda: parent.productDetails('placaVideo', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        mousepad_details.clicked.connect   (lambda: parent.productDetails('mousepad', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        fone_details.clicked.connect       (lambda: parent.productDetails('fone', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        ram_details.clicked.connect        (lambda: parent.productDetails('ram', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
        gabinete_details.clicked.connect   (lambda: parent.productDetails('gabinete', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.'))
