from CreateOne import *
from Constants import STYLES

class CreateMany:
    def firstScreen(parent):  
        parent.createOne.item (parent,  10, 100, "imagens/Medias/pc_m.jpg",          "Supremacy Ultra: o ápice da tecnologia encapsulada em um computador excepcionalmente poderoso e esteticamente impressionante.")
        parent.createOne.item (parent, 330, 100, "imagens/Medias/teclado_m.jpg",     "ultra type: teclado mecânico com uma experiência de digitação excepcional! Combina durabilidade, precisão, conforto e um design elegante.")
        parent.createOne.item (parent, 650, 100, "imagens/Medias/monitor_m.jpg",     "VisionXtreme: Com resolução Ultra HD 4K, taxa de atualização de 144Hz e tecnologia HDR, oferece imagens nítidas para uma experiência visual imersiva.")
        parent.createOne.item (parent, 970, 100, "imagens/Medias/mouse_m.jpg",       "PhantomGrip: o Mouse Gamer de Elite Projetado para proporcionar precisão, velocidade e conforto como nenhum outro.")
        parent.createOne.item (parent,  10, 240, "imagens/Medias/processador_m.jpg", "HyperCore: Perfeito para Desempenho Computacional! Equipado com tecnologia de ponta, tem potência para lidar com as tarefas mais exigentes")
        parent.createOne.item (parent, 330, 240, "imagens/Medias/ssd_m.jpg",         "TurboDrive: o SSD de Elite completo! Com capacidades de armazenamento e velocidades de leitura/gravação ultra-rápidas")
        parent.createOne.item (parent, 650, 240, "imagens/Medias/cooler_m.jpg",      "FrostBlast: o Cooler perfeito para seu Desempenho de Refrigeração! Oferece resfriamento excepcional e silencio para seu sistema.")
        parent.createOne.item (parent, 970, 240, "imagens/Medias/placaVideo_m.jpg",  "TurBoost 9000X tem uma potência de processamento gráfico projetada para elevar sua experiência a novos patamares") 
        parent.createOne.item (parent,  10, 380, "imagens/Medias/mousepad_m.jpg",    "HyperGlide Pro: o Mousepad de Elite para sua Precisão e Conforto de Movimento!") 
        parent.createOne.item (parent, 330, 380, "imagens/Medias/fone_m.jpg",        "SonicBlast 8000X: projetados para proporcionar áudio imersivo e de alta qualidade com tecnologia de cancelamento de ruído ativo.") 
        parent.createOne.item (parent, 650, 380, "imagens/Medias/ram_m.jpg",         "RAM Triforce: uma solução poderosa que oferece não uma, mas três memórias RAM de alta velocidade, Com capacidade total de 24GB (3x8GB)") 
        parent.createOne.item (parent, 970, 380, "imagens/Medias/gabinete_m.jpg",    "Gamer Turbo X, uma escolha para os entusiastas de PC que buscam o máximo de estilo. Garante iluminação RGB personalizável e amplo espaço interno") 


    def itemsToAdd(parent):
        pc_add          = parent.createOne.button(parent, '+',  100, 190, 25, 25, STYLES["add_button"])
        teclado_add     = parent.createOne.button(parent, '+',  420, 190, 25, 25, STYLES["add_button"])
        monitor_add     = parent.createOne.button(parent, '+',  740, 190, 25, 25, STYLES["add_button"])
        mouse_add       = parent.createOne.button(parent, '+', 1060, 190, 25, 25, STYLES["add_button"])
        processador_add = parent.createOne.button(parent, '+',  100, 330, 25, 25, STYLES["add_button"])
        ssd_add         = parent.createOne.button(parent, '+',  420, 330, 25, 25, STYLES["add_button"])
        cooler_add      = parent.createOne.button(parent, '+',  740, 330, 25, 25, STYLES["add_button"])
        placaVideo_add  = parent.createOne.button(parent, '+', 1060, 330, 25, 25, STYLES["add_button"])
        mousepad_add    = parent.createOne.button(parent, '+',  100, 470, 25, 25, STYLES["add_button"])
        fone_add        = parent.createOne.button(parent, '+',  420, 470, 25, 25, STYLES["add_button"])
        ram_add         = parent.createOne.button(parent, '+',  740, 470, 25, 25, STYLES["add_button"])
        gabinete_add    = parent.createOne.button(parent, '+', 1060, 470, 25, 25, STYLES["add_button"])
        
        pc_add.clicked.connect         (lambda: parent.onAddToCartClicked("pc"))
        teclado_add.clicked.connect    (lambda: parent.onAddToCartClicked("teclado"))
        monitor_add.clicked.connect    (lambda: parent.onAddToCartClicked("monitor"))
        mouse_add.clicked.connect      (lambda: parent.onAddToCartClicked("mouse"))       
        mousepad_add.clicked.connect   (lambda: parent.onAddToCartClicked("mousepad"))
        processador_add.clicked.connect(lambda: parent.onAddToCartClicked("processador"))
        ssd_add.clicked.connect        (lambda: parent.onAddToCartClicked("ssd"))
        cooler_add.clicked.connect     (lambda: parent.onAddToCartClicked("cooler"))
        placaVideo_add.clicked.connect (lambda: parent.onAddToCartClicked("placaVideo"))
        fone_add.clicked.connect       (lambda: parent.onAddToCartClicked("fone"))
        ram_add.clicked.connect        (lambda: parent.onAddToCartClicked("ram"))
        gabinete_add.clicked.connect   (lambda: parent.onAddToCartClicked("gabinete"))


    def itemsToRemove(parent):
        pc_remove          = parent.createOne.button(parent, '-',  100, 190, 25, 25, STYLES["remove_button"])
        teclado_remove     = parent.createOne.button(parent, '-',  420, 190, 25, 25, STYLES["remove_button"])
        monitor_remove     = parent.createOne.button(parent, '-',  740, 190, 25, 25, STYLES["remove_button"])
        mouse_remove       = parent.createOne.button(parent, '-', 1060, 190, 25, 25, STYLES["remove_button"])
        processador_remove = parent.createOne.button(parent, '-',  100, 330, 25, 25, STYLES["remove_button"])
        ssd_remove         = parent.createOne.button(parent, '-',  420, 330, 25, 25, STYLES["remove_button"])
        cooler_remove      = parent.createOne.button(parent, '-',  740, 330, 25, 25, STYLES["remove_button"])
        placaVideo_remove  = parent.createOne.button(parent, '-', 1060, 330, 25, 25, STYLES["remove_button"])
        mousepad_remove    = parent.createOne.button(parent, '-',  100, 470, 25, 25, STYLES["remove_button"])
        fone_remove        = parent.createOne.button(parent, '-',  420, 470, 25, 25, STYLES["remove_button"])
        ram_remove         = parent.createOne.button(parent, '-',  740, 470, 25, 25, STYLES["remove_button"])
        gabinete_remove    = parent.createOne.button(parent, '-', 1060, 470, 25, 25, STYLES["remove_button"])

        pc_remove.clicked.connect         (lambda: parent.removeFromCart("pc"))
        teclado_remove.clicked.connect    (lambda: parent.removeFromCart("teclado"))
        monitor_remove.clicked.connect    (lambda: parent.removeFromCart("monitor"))
        mouse_remove.clicked.connect      (lambda: parent.removeFromCart("mouse"))       
        processador_remove.clicked.connect(lambda: parent.removeFromCart("processador"))
        ssd_remove.clicked.connect        (lambda: parent.removeFromCart("ssd"))
        cooler_remove.clicked.connect     (lambda: parent.removeFromCart("cooler"))
        placaVideo_remove.clicked.connect (lambda: parent.removeFromCart("placaVideo"))
        mousepad_remove.clicked.connect   (lambda: parent.removeFromCart("mousepad"))
        fone_remove.clicked.connect       (lambda: parent.removeFromCart("fone"))
        ram_remove.clicked.connect        (lambda: parent.removeFromCart("ram"))
        gabinete_remove.clicked.connect   (lambda: parent.removeFromCart("gabinete"))


    def itemDetails(parent):
        pc_details          = parent.createOne.button(parent, '?',  100, 190, 25, 25, STYLES["details_button"])
        teclado_details     = parent.createOne.button(parent, '?',  420, 190, 25, 25, STYLES["details_button"])
        monitor_details     = parent.createOne.button(parent, '?',  740, 190, 25, 25, STYLES["details_button"])
        mouse_details       = parent.createOne.button(parent, '?', 1060, 190, 25, 25, STYLES["details_button"])
        processador_details = parent.createOne.button(parent, '?',  100, 330, 25, 25, STYLES["details_button"])
        ssd_details         = parent.createOne.button(parent, '?',  420, 330, 25, 25, STYLES["details_button"])
        cooler_details      = parent.createOne.button(parent, '?',  740, 330, 25, 25, STYLES["details_button"])
        placaVideo_details  = parent.createOne.button(parent, '?', 1060, 330, 25, 25, STYLES["details_button"])
        mousepad_details    = parent.createOne.button(parent, '?',  100, 470, 25, 25, STYLES["details_button"])
        fone_details        = parent.createOne.button(parent, '?',  420, 470, 25, 25, STYLES["details_button"])
        ram_details         = parent.createOne.button(parent, '?',  740, 470, 25, 25, STYLES["details_button"])
        gabinete_details    = parent.createOne.button(parent, '?', 1060, 470, 25, 25, STYLES["details_button"])

        pc_details.clicked.connect          (lambda: parent.productDetails("pc", "O Supremacy Ultra é o ápice da tecnologia, encapsulando um poder excepcional e uma estética impressionante em um único computador.\n\nEquipado com o processador HyperCore, este PC oferece desempenho computacional inigualável, pronto para enfrentar as tarefas mais exigentes com facilidade e eficiência.\n\nCom a placa de vídeo TurBoost 9000X, você experimenta gráficos de última geração, proporcionando uma qualidade visual surpreendente e uma fluidez incomparável para jogos, edição de vídeo e aplicações de realidade virtual.\n\nO Supremacy Ultra é complementado por 24GB de RAM Triforce, garantindo multitarefa eficiente e um desempenho suave em todas as atividades.",
                                                                          "O armazenamento é rápido e confiável com o SSD TurboDrive, que oferece velocidades de leitura/gravação ultra-rápidas, garantindo que o sistema e os aplicativos carreguem em um piscar de olhos. O sistema de refrigeração é gerenciado pelo cooler FrostBlast, que mantém o sistema resfriado e silencioso mesmo sob carga máxima.\n\nTodo esse hardware de ponta é alojado no gabinete Gamer Turbo X, que combina estilo e funcionalidade com sua iluminação RGB personalizável e amplo espaço interno para futuras expansões.\n\nPara completar a experiência, o Supremacy Ultra vem com periféricos de elite, incluindo o teclado mecânico Ultra Type, que oferece uma digitação precisa e confortável, o mouse gamer PhantomGrip, que garante movimentos rápidos e exatos, e o mousepad HyperGlide Pro, que proporciona uma superfície perfeita para o seu mouse.\n\nOs fones SonicBlast 8000X imergem você em um áudio de alta qualidade com cancelamento de ruído ativo, enquanto o monitor VisionXtreme 4K oferece uma experiência visual imersiva com resolução Ultra HD, taxa de atualização de 144Hz e tecnologia HDR.\n\nEm resumo, o Supremacy Ultra é a escolha definitiva para quem busca o melhor em desempenho, estilo e tecnologia, proporcionando uma experiência computacional de elite em todos os aspectos."))
        
        teclado_details.clicked.connect     (lambda: parent.productDetails("teclado", "O Ultra Type é um teclado mecânico que redefine o padrão da digitação, oferecendo uma experiência excepcional que combina durabilidade, precisão e conforto.\n\nEquipado com switches mecânicos de alta qualidade, o Ultra Type proporciona uma resposta tátil e auditiva única a cada pressionar de tecla, resultando em uma velocidade de digitação incomparável.\n\nSeu design ergonômico foi meticulosamente desenvolvido para reduzir a fadiga durante longas sessões de uso, com teclas ligeiramente côncavas que se adaptam perfeitamente aos seus dedos, garantindo uma postura natural e confortável.\n\nAlém disso, o Ultra Type conta com um sistema de iluminação RGB personalizável, permitindo que você ajuste as cores e os efeitos de iluminação conforme o seu gosto, criando um ambiente de trabalho ou jogo imersivo e estiloso.",
                                                                          "A aparência do Ultra Type é uma combinação de elegância e excentricidade.\n\nSua estrutura robusta de alumínio escovado confere ao teclado uma durabilidade impressionante, enquanto seu layout compacto e moderno economiza espaço na sua mesa sem comprometer a funcionalidade.\n\nCom conectividade versátil, o Ultra Type pode ser utilizado tanto via cabo USB quanto via conexão sem fio Bluetooth, oferecendo a flexibilidade que você precisa para trabalhar ou jogar em qualquer lugar.\n\nAdicionalmente, o teclado é compatível com diversas plataformas, incluindo Windows, macOS, e dispositivos móveis, tornando-o uma escolha ideal para qualquer usuário que busca eficiência e estilo.\n\nEm resumo, o Ultra Type é o teclado definitivo para quem valoriza uma experiência de digitação superior, combinando desempenho excepcional com um design arrojado e funcional."))
        
        monitor_details.clicked.connect     (lambda: parent.productDetails("monitor", "O VisionXtreme é um monitor que eleva a experiência visual a um novo patamar, combinando resolução Ultra HD 4K com uma taxa de atualização de 144Hz e tecnologia HDR.\n\nCom 3840 x 2160 pixels, o VisionXtreme oferece uma clareza impressionante, revelando os mínimos detalhes com uma nitidez inigualável. A alta taxa de atualização de 144Hz garante uma fluidez excepcional nas cenas de ação, eliminando borrões e garantindo que até os movimentos mais rápidos sejam exibidos com precisão.\n\nA tecnologia HDR (High Dynamic Range) aprimora ainda mais a qualidade das imagens, proporcionando cores mais vibrantes e um contraste mais profundo, resultando em uma experiência visual que é ao mesmo tempo realista e envolvente.",
                                                                          "O design do VisionXtreme é uma obra de arte em si: com uma moldura ultrafina, o monitor maximiza a área de visualização, oferecendo uma aparência elegante e moderna que se encaixa perfeitamente em qualquer ambiente, seja no escritório ou em casa.\n\nAlém disso, o VisionXtreme possui diversas opções de conectividade, incluindo portas HDMI, DisplayPort e USB-C, garantindo compatibilidade com uma ampla gama de dispositivos.\n\nO suporte ajustável permite que você encontre a posição de visualização perfeita, enquanto o modo de baixa luz azul e a tecnologia anti-flicker ajudam a reduzir a fadiga ocular durante longas sessões de uso.\n\nEm suma, o VisionXtreme é o monitor ideal para quem busca uma experiência visual imersiva, combinando desempenho de ponta com um design sofisticado e funcionalidades versáteis."))
       
        mouse_details.clicked.connect       (lambda: parent.productDetails("mouse", "O PhantomGrip é o mouse gamer de elite que redefine o conceito de desempenho, projetado para proporcionar precisão, velocidade e conforto incomparáveis.\n\nEquipado com um sensor óptico de alta precisão, o PhantomGrip oferece um rastreamento perfeito e uma resposta ultrarrápida, garantindo que cada movimento seja registrado com exatidão milimétrica.\n\nCom uma taxa de polling de 1000Hz e ajustes de DPI que vão de 200 a 16.000, o PhantomGrip permite personalizar a sensibilidade de acordo com suas necessidades, seja para movimentos rápidos em jogos de FPS ou para a precisão milimétrica necessária em jogos de estratégia.\n\nA tecnologia de switches mecânicos Omron garante cliques nítidos e responsivos, com uma durabilidade projetada para suportar até 50 milhões de cliques.",
                                                                          "O design do PhantomGrip é uma combinação de estética moderna e ergonomia avançada. Com uma estrutura leve e uma forma contornada que se adapta perfeitamente à mão, este mouse oferece um conforto excepcional, mesmo durante longas maratonas de jogo.\n\nA superfície texturizada e os grips laterais de borracha proporcionam um controle firme e seguro, enquanto os botões programáveis permitem uma personalização completa, adaptando o mouse ao seu estilo de jogo.\n\nAlém disso, o PhantomGrip possui uma iluminação RGB personalizável, com efeitos de luz dinâmicos que podem ser sincronizados com outros dispositivos para uma experiência de jogo imersiva.\n\nEm resumo, o PhantomGrip é o mouse definitivo para gamers que exigem o máximo de precisão, velocidade e conforto, oferecendo uma performance de elite em um design sofisticado e funcional."))  
             
        processador_details.clicked.connect (lambda: parent.productDetails("processador", "O HyperCore é o processador perfeito para desempenho computacional, projetado para enfrentar as tarefas mais exigentes com facilidade e eficiência.\n\nEquipado com a mais avançada tecnologia de ponta, o HyperCore oferece uma potência excepcional que redefine o conceito de velocidade e capacidade de processamento. Com múltiplos núcleos e threads, este processador é ideal para multitarefas intensivas, permitindo que você execute várias aplicações simultaneamente sem perder desempenho.\n\nSeja para renderização de vídeos em alta resolução, simulações complexas ou jogos de última geração, o HyperCore proporciona uma experiência fluida e sem interrupções, elevando seu fluxo de trabalho a novos patamares.",
                                                                          "Além de sua impressionante potência, o HyperCore destaca-se pela eficiência energética e pelo gerenciamento térmico aprimorado, garantindo um desempenho consistente mesmo sob cargas extremas.\n\nA arquitetura avançada do HyperCore oferece velocidades de clock surpreendentes e um cache inteligente que otimiza o acesso a dados, reduzindo latências e aumentando a responsividade do sistema.\n\nCom suporte a tecnologias de última geração, como PCIe 4.0 e memória DDR5, o HyperCore está preparado para o futuro, oferecendo compatibilidade com os componentes mais modernos.\n\nEm resumo, o HyperCore é a escolha definitiva para quem busca um processador capaz de lidar com qualquer desafio computacional, combinando potência, eficiência e inovação em um único pacote robusto e confiável."))

        ssd_details.clicked.connect         (lambda: parent.productDetails("ssd", "O TurboDrive é o SSD de elite que redefine o conceito de armazenamento de dados, oferecendo capacidades impressionantes e velocidades de leitura/gravação ultra-rápidas.\n\nProjetado para proporcionar um desempenho superior, o TurboDrive utiliza a mais avançada tecnologia de memória flash NAND, garantindo transferências de dados em velocidades que transformam a maneira como você interage com seus arquivos.\n\nCom velocidades de leitura que podem alcançar até 3500 MB/s e gravações de até 3000 MB/s, o TurboDrive permite que você inicie o sistema operacional, carregue aplicativos e transfira arquivos grandes em uma fração do tempo comparado aos discos rígidos tradicionais.",
                                                                          "Além de sua velocidade incrível, o TurboDrive se destaca pela alta confiabilidade e durabilidade, tornando-o ideal para uso intensivo e prolongado.\n\nCom capacidades de armazenamento que variam de 256 GB a 2 TB, este SSD oferece opções flexíveis para atender às suas necessidades específicas, seja para armazenar uma vasta biblioteca de jogos, projetos de trabalho complexos ou coleções multimídia.\n\nO TurboDrive também incorpora tecnologias avançadas de correção de erros e gerenciamento de desgaste, garantindo a integridade dos dados e uma vida útil prolongada do dispositivo.\n\nEm resumo, o TurboDrive é o SSD definitivo para quem busca uma combinação de desempenho ultrarrápido, alta capacidade de armazenamento e confiabilidade incomparável, transformando sua experiência computacional em todos os aspectos."))

        cooler_details.clicked.connect      (lambda: parent.productDetails("cooler", "O FrostBlast é o cooler definitivo para quem busca um desempenho de refrigeração excepcional aliado ao silêncio absoluto.\n\nProjetado com tecnologia de ponta, o FrostBlast garante que seu sistema se mantenha em temperaturas ideais mesmo sob as cargas de trabalho mais intensas.\n\nEquipado com uma combinação de heatpipes de cobre e aletas de alumínio, este cooler maximiza a dissipação de calor, proporcionando um resfriamento eficiente e consistente.\n\nO ventilador de alta performance, com rolamentos fluidodinâmicos, opera de maneira incrivelmente silenciosa, permitindo que você se concentre em suas tarefas sem o incômodo de ruídos excessivos.",
                                                                          "Além de sua eficiência térmica e operação silenciosa, o FrostBlast apresenta um design moderno e elegante, que complementa qualquer configuração de PC.\n\nCom LEDs RGB personalizáveis, você pode ajustar a iluminação para sincronizar com o restante do seu hardware, criando uma estética visualmente fantástica.\n\nA instalação é simplificada graças ao sistema de montagem universal, compatível com uma ampla gama de sockets de CPU, tanto Intel quanto AMD.\n\nEm suma, o FrostBlast é a escolha perfeita para quem busca um cooler que combine resfriamento excepcional, operação silenciosa e um design atraente, garantindo que seu sistema funcione com desempenho máximo e estilo inigualável."))

        placaVideo_details.clicked.connect  (lambda: parent.productDetails("placaVideo", "A TurBoost 9000X é a placa de vídeo que eleva sua experiência gráfica a novos patamares, combinando velocidade, eficiência e potência líderes de mercado.\n\nCom uma arquitetura avançada e uma quantidade impressionante de núcleos CUDA, a TurBoost 9000X oferece um desempenho gráfico incomparável, permitindo que você desfrute dos jogos mais recentes em configurações máximas, com taxas de quadros ultrassuaves e uma qualidade visual de tirar o fôlego.\n\nO suporte a Ray Tracing em tempo real e a tecnologia DLSS (Deep Learning Super Sampling) da NVIDIA garantem gráficos hiper-realistas e uma eficiência superior, proporcionando uma imersão total em seus jogos e aplicações de realidade virtual.",
                                                                          "Além de seu poder de processamento gráfico bruto, a TurBoost 9000X destaca-se pela sua eficiência energética e pelo design térmico inovador.\n\nCom um sistema de refrigeração triplo e ventiladores de alta performance, a placa mantém temperaturas baixas mesmo nas sessões de uso mais intensas, garantindo um funcionamento estável e duradouro.\n\nO design elegante, com iluminação RGB personalizável, permite que você adapte a aparência da placa ao restante do seu setup, criando uma estética coesa e impressionante.\n\nA TurBoost 9000X também oferece uma conectividade robusta, com múltiplas saídas HDMI e DisplayPort, além de suporte a monitores 4K e 8K, tornando-a ideal para profissionais de edição de vídeo, designers gráficos e gamers exigentes.\n\nEm resumo, a TurBoost 9000X é a placa de vídeo definitiva para quem busca o melhor em desempenho gráfico, eficiência e estilo, transformando cada sessão de uso em uma experiência extraordinária."))

        mousepad_details.clicked.connect    (lambda: parent.productDetails("mousepad", "O HyperGlide Pro é o mousepad de elite, projetado para proporcionar precisão e conforto de movimento incomparáveis.\n\nCom uma superfície de microtextura otimizada, o HyperGlide Pro oferece um equilíbrio perfeito entre velocidade e controle, permitindo movimentos rápidos e precisos com qualquer tipo de sensor de mouse.\n\nSeja para jogos intensos ou para tarefas de design detalhadas, este mousepad garante uma resposta exata e consistente, ajudando você a alcançar um desempenho superior em todas as atividades.",
                                                                          "Além de sua excepcional funcionalidade, o HyperGlide Pro se destaca pelo conforto e durabilidade.\n\nA base emborrachada antiderrapante mantém o mousepad firmemente no lugar, evitando deslizamentos indesejados durante o uso.\n\nCom bordas reforçadas costuradas, o HyperGlide Pro resiste ao desgaste e ao desfiamento, garantindo uma longa vida útil. A superfície de baixa fricção reduz a fadiga do pulso e da mão, proporcionando uma experiência de uso confortável mesmo em sessões prolongadas.\n\nEm resumo, o HyperGlide Pro é o mousepad ideal para quem busca precisão, conforto e durabilidade, transformando cada movimento em uma vantagem competitiva."))

        fone_details.clicked.connect        (lambda: parent.productDetails("fone", "O SonicBlast 8000X é o fone de ouvido projetado para proporcionar uma experiência de áudio imersiva e de alta qualidade, redefinindo os padrões de som.\n\nEquipado com drivers de última geração, o SonicBlast 8000X oferece uma clareza cristalina e uma profundidade sonora impressionante, permitindo que você ouça cada detalhe com precisão excepcional.\n\nA tecnologia de cancelamento de ruído ativo (ANC) isola você do mundo exterior, eliminando distrações e criando um ambiente auditivo perfeito, seja para ouvir música, jogar ou assistir filmes.",
                                                                          "Além de sua superioridade sonora, o SonicBlast 8000X destaca-se pelo conforto e pelo design elegante.\n\nCom almofadas auriculares em espuma de memória e uma faixa ajustável, este fone de ouvido proporciona um ajuste perfeito e confortável para longas sessões de uso. A estrutura leve e os materiais de alta qualidade garantem durabilidade e um uso prolongado sem desconforto.\n\nControles intuitivos no fone permitem fácil ajuste de volume, troca de faixas e atendimento de chamadas, enquanto a conectividade sem fio Bluetooth de última geração assegura uma conexão estável e de baixa latência.\n\nOu seja, o SonicBlast 8000X é a escolha ideal para quem busca áudio de alta qualidade, conforto e tecnologia avançada, oferecendo uma experiência auditiva verdadeiramente imersiva e satisfatória."))

        ram_details.clicked.connect         (lambda: parent.productDetails("ram", "A RAM Triforce é uma solução poderosa e inovadora, projetada para elevar o desempenho do seu sistema com suas três memórias RAM de alta velocidade.\n\nCom uma capacidade total de 24GB, dividida em três módulos de 8GB cada, a RAM Triforce oferece uma combinação perfeita de velocidade, eficiência e estabilidade.\n\nIdeal para gamers, profissionais de edição de vídeo e entusiastas de tecnologia, essa configuração tripla permite uma multitarefa eficiente e um processamento fluido de aplicações pesadas, garantindo que seu sistema opere com máxima performance.",
                                                                          "Além de sua impressionante capacidade e velocidade, a RAM Triforce se destaca pelo design elegante e pela construção robusta.\n\nOs módulos são equipados com dissipadores de calor de alumínio anodizado, que não apenas melhoram a estética do seu setup, mas também asseguram uma dissipação térmica eficaz, mantendo as temperaturas sob controle mesmo durante as operações mais intensas.\n\nCompatível com as mais recentes plataformas e suportando overclocking, a RAM Triforce permite que você ajuste e otimize o desempenho de acordo com suas necessidades específicas.\n\nPor fim, RAM Triforce é a escolha ideal para quem busca potência, velocidade e confiabilidade, proporcionando uma experiência computacional aprimorada e sem precedentes."))

        gabinete_details.clicked.connect    (lambda: parent.productDetails("gabinete", "O Gamer Turbo X é o gabinete perfeito para os entusiastas de PC que buscam o máximo em estilo e funcionalidade.\n\nCom um design moderno e arrojado, o Gamer Turbo X se destaca pela sua iluminação RGB personalizável, que permite criar um espetáculo de luzes único e sincronizado com o restante do seu setup.\n\nAs amplas janelas de vidro temperado oferecem uma visão clara do interior do gabinete, permitindo que você exiba seus componentes com orgulho e acompanhe a estética vibrante e dinâmica.",
                                                                          "Além de sua aparência impressionante, o Gamer Turbo X é projetado para oferecer um amplo espaço interno, acomodando facilmente as mais poderosas configurações de hardware.\n\nCompatível com placas-mãe ATX, micro-ATX e mini-ITX, este gabinete oferece suporte para placas gráficas de grande porte e sistemas de refrigeração líquida, garantindo que seu sistema permaneça resfriado mesmo sob cargas intensas.\n\nA gestão de cabos é facilitada por um layout interno inteligente, permitindo uma organização limpa e eficiente, enquanto as baias removíveis e slots de expansão proporcionam flexibilidade para futuras atualizações.\n\nEm resumo, o Gamer Turbo X é a escolha ideal para quem busca um gabinete que combine estilo, espaço e funcionalidade, garantindo uma experiência de construção de PC verdadeiramente excepcional."))